blog/urls.py
from . import views
from django.views import View
from django.urls import path

urlpatterns = [
    path(
        "blog-post-list", views.BlogListView.as_view(), name="blog-post-list"),
    path("<slug:slug>", views.BlogDetailView.as_view(), name="detail_view"),
]

enigma_machine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('bookings.urls')),
    path('user_profiles/', include('user_profiles.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('rooms/', include('rooms.urls')),
    path('faq/', include('faq.urls')),
]

faq/urls.py
from . import views
from django.views import View
from django.urls import path

urlpatterns = [
     path("faq", views.FaqList, name="faq"),
]

blog/models.py
from django.db import models
from cloudinary.models import CloudinaryField


class BlogPost(models.Model):
    TAGS = [
        ("Blog", "Blog"),
        ("Promotion", "Promotion"),
        ("Sale", "Sale"),
        ("News", "News"),
        ("Partner Advert", "Partner Advert"),
        ("Holiday", "Holiday"),
        ("B.T.S", "B.T.S"),
        ("Meet the Staff", "Meet the Staff"),
    ]

    blog_title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    tags = models.CharField(max_length=200, choices=TAGS, null=True)
    blog_image = CloudinaryField("detail image", default="placeholder")
    blog_small_image = CloudinaryField("thumbnail", default="placeholder")
    blog_blurb = models.TextField(blank=True)
    blog_content = models.TextField()
    posted_date = models.DateField(auto_now=False)
    meta_tags = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ["-posted_date"]

    def __str__(self):
        return self.blog_title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogPost
from django.views import generic, View

# Collects all the BlogPost items from database
# to render to the template


class BlogListView(generic.ListView):
    model = BlogPost
    queryset = BlogPost.objects.all()
    template_name = "blog/blog_posts.html"

# When user selects one blogpost the slug is used
# to query the database and collect the additional
# information for said blogpost, while also sending
# the current blog items to render as a side window


class BlogDetailView(View):
    def get(self, request, slug, *args, **kwargs):
        queryset = BlogPost.objects.all()
        blog = get_object_or_404(queryset, slug=slug)
        content = blog.blog_content
        content_parts = content.split("\n")
        template = "blog/blog_post_detail.html"
        context = {
            "blog": blog,
            "content_parts": content_parts,
            "blog_list": queryset,
        }
        return render(request, template, context)

    def post(self, request, slug, *args, **kwargs):
        template = "blog/blog_post_detail.html"
        return render(request, template)

blog/templates/blog/blog_post_detail.html
{% extends "base.html" %}
<!-- Pass the active page variable to the base template -->
{% block scripts %}
{% with active_page='blog' %}
{{ block.super }}
{% endwith %}
{% endblock %}
{% block content %}
<div class="breadcrumbs d-flex align-items-center"
  style="background-image: url('https://res.cloudinary.com/dl02kivmy/image/upload/c_scale,w_1800/v1684932491/shutterstock_12530514342_gb5a4j.jpg');">
  <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">
    <h2>Blog Posts</h2>
  </div>
</div>
<section id="blog" class="blog">
  <div class="container" data-aos="fade-up" data-aos-delay="100">
    <div class="row g-5">
      <div class="col-lg-8">
        <article class="blog-details">
          <div class="post-img">
            <img src="{{blog.blog_image.url}}" alt="" class="img-fluid">
          </div>
          <h2 class="title">{{ blog.blog_title }}</h2>
          <div class="meta-top">
            <ul>
              <li class="d-flex align-items-center"><i class="bi bi-clock"></i> Jan 1, 2022</li>
            </ul>
          </div><!-- End meta top -->
          <div class="content">
            {% for paragraph in content_parts %}
            {% if forloop.counter == 4 %}
            <blockquote>
              <p>{{blog.blog_blurb}}</p>
            </blockquote>
            <p>{{ paragraph }}</p>
            {% else %}
            <p>{{paragraph}}</p>
            {% endif %}
            {% endfor %}
          </div><!-- End post content -->
          <div class="meta-bottom">
            <i class="bi bi-folder"></i>
            <ul class="cats">
              <li><a href="#">{{blog.tags}}</a></li>
            </ul>
          </div><!-- End meta bottom -->
        </article><!-- End blog post -->
      </div>
      <div class="col-lg-4">
        <div class="sidebar">
          <div class="sidebar-item recent-posts">
            <h3 class="sidebar-title">Recent Posts</h3>
            <div class="mt-3">
              {% for blog in blog_list %}
              <div class="post-item mt-3">
                <img src="{{blog.blog_image.url}}" alt="">
                <div>
                  <h4><a href="{% url 'detail_view' blog.slug %}">{{blog.blog_title}}</a></h4>
                  <div class="blog_time">{{blog.posted_date}}</div>
                </div>
              </div><!-- End recent post item-->
              {% endfor %}
            </div>
          </div><!-- End Blog Sidebar -->
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

blog/templates/blog/blog_posts.html
{% extends "base.html" %}
<!-- Pass the active page variable to the base template -->
{% block scripts %}
{% with active_page='blog' %}
{{ block.super }}
{% endwith %}
{% endblock %}
{% block content %}
<div class="breadcrumbs d-flex align-items-center"
  style="background-image: url('https://res.cloudinary.com/dl02kivmy/image/upload/c_scale,w_1800/v1684932491/shutterstock_12530514342_gb5a4j.jpg');">
  <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">
    <h2>Blog Posts</h2>
  </div>
</div>
{% if blogpost_list%}
<section id="blog" class="blog">
  <div class="container" data-aos="fade-up" data-aos-delay="100">
    <div class="row gy-4 posts-list">
      {% for blogpost in blogpost_list %}
      <div class="col-xl-4 col-md-6">
        <div class="post-item position-relative h-100">
          {% if "placeholder" in blogpost.blog_image.url %}
          <div class="post-img position-relative overflow-hidden">
            <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" class="img-fluid" alt="">
            <span class="post-date">{{blogpost.posted_date}}</span>
          </div>
          {% else %}
          <div class="post-img position-relative overflow-hidden">
            <img src="{{ blogpost.blog_small_image.url }}" class="img-fluid" alt="">
            <span class="post-date">{{blogpost.posted_date}}</span>
          </div>
          {% endif %}
          <div class="post-content d-flex flex-column">
            <h3 class="post-title">{{blogpost.blog_title}}</h3>
            <div class="meta d-flex align-items-center">
              <div class="d-flex align-items-center">
                <i class="bi bi-folder2"></i> <span class="ps-2">{{blogpost.tags}}</span>
              </div>
            </div>
            <p>
              {{blogpost.blog_blurb}}
            </p>
            <hr>
            <a href="{% url 'detail_view' blogpost.slug %}" class="readmore stretched-link"><span>Read More</span><i
                class="bi bi-arrow-right"></i></a>
          </div>
        </div>
      </div><!-- End post list item -->
      {% endfor %}
    </div>
  </div>
</section><!-- End Blog Section -->
{% else %}
<h1>No blog posts are available</h1>
{% endif %}
{% endblock %}